ignore-paths:
  - manage.py
  - website/settings/
  - website/gunicorn.py
test-warnings: true
strictness: high
doc-warnings: false
member-warnings: true
max-line-length: 120
uses:
    - django
    - celery
