version: 2.1

commands:
  save_cache_pip:
    steps:
      - save_cache:
          key: pip3-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
          paths:
            - ".pip-cache/"
  restore_cache_pip:
    steps:
      - restore_cache:
          key: pip3-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
  save_cache_venv:
    steps:
      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
          paths:
            - ".venv/"
  restore_cache_venv:
    steps:
      - restore_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
  set_test_env:
    steps:
      - run:
          command: |
            cp website/settings/.env.local website/settings/.env
  set_test_env_with_psql:
    steps:
      - run:
          command: |
            sed -i s/DATABASE_URL.*/DATABASE_URL=postgres:\/\/postgres:postgres@localhost:5432\/postgres\/g website/settings/.env
  save_test_env:
    steps:
      - save_cache:
          key: env-{{ .Branch }}-{{ checksum "website/settings/.env.local" }}
          paths:
            - "website/settings/.env"
  restore_test_env:
    steps:
      - restore_cache:
          key: env-{{ .Branch }}-{{ checksum "website/settings/.env.local" }}
executors:
  docker-executor:
    docker:
      - image: python:3.9.4-buster # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
  docker-executor-with-psql:
    docker:
      - image: python:3.9.4-buster # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # Service container image available at `host: localhost`
      - image: postgres:13.2-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

jobs:
  build_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.2
      - checkout
      - run:
          command: |
            docker-compose build
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_pip
      - restore_cache_venv
      - set_test_env
      - run:
          command: |
            python3 -m venv .venv/
            source .venv/bin/activate
            pip3 install -U pip
            pip3 install -r requirements/local.txt --cache-dir .pip-cache/
      - save_cache_pip
      - save_cache_venv
      - save_test_env
  test-migrations:
    executor: docker-executor-with-psql
    steps:
      - checkout
      - restore_cache_venv
      - restore_test_env
      - set_test_env_with_psql
      - run:
          command: |
            source .venv/bin/activate
            ./manage.py migrate
  prospector:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_venv
      - run:
          command: |
            source .venv/bin/activate
            prospector
  black:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_venv
      - run:
          command: |
            source .venv/bin/activate
            black website --check
  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_venv
      - restore_test_env
      - run:
          command: |
            source .venv/bin/activate
            pytest --cov
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: coverage.xml
          destination: tr2
      - store_artifacts:
          path: htmlcov
          destination: tr3
workflows:
  main:
    jobs:
      - build_docker_image
      - build
      - test:
          requires:
            - build
      - prospector:
          requires:
            - build
      - black:
          requires:
            - build
      - test-migrations:
          requires:
            - build
