version: 2.1

orbs:
  python: circleci/python@1.3.5

jobs:
  build-and-test:
    docker:
      - image: python:3.9.4-buster # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run:
          command: |
            pip3 install -r requirements/local.txt
      - run:
          command: |
            python3 manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  main:
    jobs:
      - build-and-test
