version: 2.1

commands:
  save_cache_pip:
    steps:
      - save_cache:
          key: pip3-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
          paths:
            - ".pip-cache/"
  restore_cache_pip:
    steps:
      - restore_cache:
          key: pip3-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
  save_cache_venv:
    steps:
      - save_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}
          paths:
            - ".venv/"
  restore_cache_venv:
    steps:
      - restore_cache:
          key: venv-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/local.txt" }}

executors:
  docker-executor:
    docker:
      - image: python:3.9.4-buster # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_pip
      - restore_cache_venv
      - run:
          command: |
            python3 -m venv .venv/
            source .venv/bin/activate
            pip3 install -r requirements/local.txt --cache-dir .pip-cache/
      - save_cache_pip
      - save_cache_venv
  prospector:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_venv
      - run:
          command: |
            source .venv/bin/activate
            prospector
  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache_venv
      - run:
          command: |
            source .venv/bin/activate
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
