version: 2.1

orbs:
  python: circleci/python@1.3.5


jobs:
  build:
    docker:
      - image: python:3.9.4-buster # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - restore_cache:
          key: pip3-{{ .Branch }}
      - run:
          command: |
            pip3 venv .venv/
            source .venv/bin/activate
            pip3 install -r requirements/local.txt --cache-dir .pip-cache/
      - save_cache:
          key: pip3-{{ .Branch }}
          paths:
            - ".pip-cache/"
      - save_cache:
          key: venv-{{ .Branch }}
          paths:
            - ".venv/"

  test:
    docker:
      - image: python:3.9.4-buster # every job must define an image for the docker executor and subsequent jobs may define a different image.
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - restore_cache:
          key: venv-{{ .Branch }}
      - run:
          command: |
            source .venv/bin/activate
            python3 manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  main:
    jobs:
      - build
      - test
